#+title: Questionario_aula_dia_22_fev

* Questões:
** 1
    - Nessa primeira aula, nos deparamos com muitos termos novos, escolha, ao menos, um deles e busque uma definição para ele (indique a referência utilizada para isso).
        Alguns termos que podem ser pesquisados:
            * interface
            * ergonomia
            * interação
            * usabilidade
            * acessibilidade
            * comunicabilidade
            * funcionalidade
*** Resposta:
Usabilidade, de acordo com a Norma NBR 9241, é “medida na qual um
produto pode ser usado por usuários específicos para alcançar objetivos específicos com
eficácia, eficiência e satisfação em um contexto específico de uso”.

referência: https://drive.google.com/file/d/1GPyDLGu-1nRW5r5SAWqqgq4JNDZc-b-H/edit


** 2
 - Conte-nos sua experiência (boa ou ruim) sobre o uso de alguma interface. Lembre-se que, assim como os exemplos apresentados em aula, não precisa ser um exemplo computacional, pois uma interface refere-se à comunicação com o usuário.

*** Resposta:
Além de experiências referentes a interfaces de softwares. Acredito que quase todos já presenciaram isso que vou relatar.
Entrando em um banco, prefeitura ou qualquer estabelecimento parecido. Entrar nele e não ter a menor ideia de como prosseguir.
Para onde eu vou? Onde que eu acesso as informação de ajuda. Aquela sensação de estar perdido e não saber para onde ir.
Uma experiência ruim que em muitos estabelecimentos desse tipo compartilham e a maioria das vezes você acaba dependendo de ajudar de outras pessoas que trabalham lá, onde não necessariamente elas trabalham para tirar dúvidas dos clients.
