#+TITLE: A Reforma Protestante
#+AUTHOR: Lucas Vianna Moog Brentano

#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [letterpaper]
# Disables table of contents
#+OPTIONS: toc:nil num:nil
#+date: 22 de março, 2023


* Introdução
Realização do quarto tema de estudo. Com base no *[[https://estadodaarte.estadao.com.br/a-reforma-protestante-e-a-genese-do-direito-moderno/][texto]]* de Davi Lago podemos extrair que a reforma protestante foi um movimento que surgiu no século XVI, liderado por figuras como Martinho Lutero e João Calvino. Esse movimento questionou a autoridade da Igreja Católica Romana, que detinha o monopólio do poder religioso na Europa Ocidental na época. A Reforma Protestante teve um impacto profundo na história da Europa, não apenas no âmbito religioso, mas também no campo do Direito, o começo do Direito que conhecemos hoje.

* Fragmentação do Poder
A Reforma Protestante teve um papel importante na secularização do Direito. Antes da Reforma, o poder religioso e político estava concentrado nas mãos do Papa e de líderes da Igreja. No entanto, com o surgimento de líderes religiosos e políticos na Europa, e cada um com sua própria interpretação da Bíblia e sua própria visão sobre como a igreja deveria ser governada, isso levou a uma fragmentação do poder religioso. Resultando no enfraquecimento do poder e a influência da Igreja Católica.
