#+TITLE: A Experiência Religiosa
#+SUBTITLE: Mídia, Religião e Sociedade
#+AUTHOR: Lucas Vianna Moog Brentano

#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [letterpaper]
# Disables table of contents
#+OPTIONS: toc:nil num:nil
#+date: 25 de fevereiro, 2023


* Introdução
Realização do primeiro tema de estudo. Destaque de dois temas dessa *[[yt:https://www.youtube.com/watch?v=BbU4zCmKufs][Entrevista]]*  discursando sobre o tema dessa semana.

* Primeiro Tema: Um novo caminho para expor a religião.
Como o Luís Mauro Sá Martino expõe na entrevista, atualmente muitas religiões diferentes estão utilizando o meio de mídias digitais.
Para conseguir uma exposição maior da religião para seus crentes e ou futuros crentes. Que consequentemente, cria uma relação diferente entre o crente e sua religião.

Com essa nova fronte de exposição, criam novas experiências e relações com a religião. Sendo o meio pelas redes sociais, televisão, rádio e entre outros
gera uma experiência diferentes do que as formas mais tradicionais.
Ressaltando que novas experiências não significam que elas são ruins ou boas, como afirma Luís Martino. São novos métodos de criar experiências religiosas.
Sendo possível ter um alcance maior nos meios que as pessoas experienciam sua religião, aumentando a possibilidade de ter uma experiência boa e agradável.

* Segundo Tema: Tema 2
asdggdsahkjgsah
asdggdsahkjgsah
asdggdsahkjgsah
asdggdsahkjgsah
asdggdsahkjgsah
asdggdsahkjgsah

* Referências:
+ Entrevista https://www.youtube.com/watch?v=BbU4zCmKufs
+ https://sites.google.com/ulbra.br/G000001GS002/t001
