#+title: Atividade_aula_2
#+TITLE: A Experiência Religiosa
#+SUBTITLE: Mídia, Religião e Sociedade
#+AUTHOR: Lucas Vianna Moog Brentano

#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [letterpaper]
# Disables table of contents
#+OPTIONS: toc:nil num:nil
#+date: 25 de fevereiro, 2023


* Introdução
Realização do segundo tema de estudo. Referente ao material estudado irei apresentar
sobre Globalização e o sentimento de culpa no contexto da religião e como ela é
afetada por eles.

* Globalização e Religião
 A globalização afeta a todos na nossa vida atual, somos um mundo conectado por diversas frentes.
 E uma delas é a nossa religião, como vivemos na época da informação os nossos conhecimentos e
informações sobre a religião também é afetada. Possibilitando o acesso e conhecimento de outras
religiões, seus conceitos e culturas. Abrindo novas portas a religiões diferentes, como contempla o *transito religioso*.
Outro ponto forte dessa mudanças e descobrimento de religiões novas e ou desconhecidas. É a mistura dos conhecimentos de várias religiões distintas,
, acontecendo o fenômeno do *sincretismo religioso*. Fazendo alterações,
misturas e remoções de conceitos de várias religiões para servir o crente em específico, muitas vezes podendo criar religiões e
maneiras de pensamento novos diferentes dos que já existem.
