#+TITLE: A Reforma Protestante
#+AUTHOR: Lucas Vianna Moog Brentano

#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [letterpaper]
# Disables table of contents
#+OPTIONS: toc:nil num:nil
#+date: 22 de março, 2023


* Introdução
Realização do quarto tema de estudo. Com base no *[[https://estadodaarte.estadao.com.br/a-reforma-protestante-e-a-genese-do-direito-moderno/][texto]]* de Davi Lago podemos extrair que a reforma protestante foi um movimento que surgiu no século XVI, liderado por figuras como Martinho Lutero e João Calvino. Esse movimento questionou a autoridade da Igreja Católica Romana, que detinha o monopólio do poder religioso na Europa Ocidental na época. A Reforma Protestante teve um impacto profundo na história da Europa, não apenas no âmbito religioso, mas também no campo do Direito.

* Fragmentação do Poder
A Reforma Protestante teve um papel importante na secularização do Direito. Antes da Reforma, o poder religioso e político estava concentrado nas mãos do Papa e de líderes da Igreja. No entanto, com o surgimento de líderes religiosos e políticos na Europa, e cada um com sua própria interpretação da Bíblia e sua própria visão sobre como a igreja deveria ser governada, isso levou a uma fragmentação do poder religioso. Resultando no enfraquecimento do poder e a influência da Igreja Católica.

* Novas Ideias
Além da fragmentação do poder, a Reforma Protestante também contribuiu para a criação de uma cultura jurídica moderna. Com a ideia de seguir um sistema jurídico seguido pela razão e não com as ideias arbitrárias da Igreja, ajudou a promover uma nova cultura jurídica que enfatizava a justiça e a igualdade perante a lei, em contraste com a visão medieval e da Igreja sobre o direito.

* Referências
+ https://estadodaarte.estadao.com.br/a-reforma-protestante-e-a-genese-do-direito-moderno/
+ https://sites.google.com/ulbra.br/G000001GS002/t004
